env:
  browser: true
  commonjs: true
  es2021: true
  node: true
extends:
  - xo
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
plugins:
  - '@typescript-eslint'
rules: {
  capitalized-comments: 0,
  new-cap: 0,
  camelcase: 0
}
