version: "3.8"

services:
  botpress:
    container_name: botpress
    build:
      context: ./
      dockerfile: .setup/build/Dockerfile
      target: dev
    image: botpress
    command: yarn dev
    environment:
      - APP_ENV=development
      - APP_PORT=8080
      - OPENAI_API_KEY=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
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    networks:
      - botpress

networks:
  botpress:
    name: "botpress"
